# If you are not familiar with YAML format just like me, read https://en.wikipedia.org/wiki/YAML
# PLEASE DON'T MODIFY THIS FILE, instead you may create a local file called `config.local.yaml`
# to overwrites this file.
srcDir: src

destDir: dist

port: 14333

packageScopes:
  - dr
  # dr-core is considered as special packages which will be loaded before other packages
  - dr-core

recipeFolder: package-recipe

nodeRoutePath: /

# enable devMode to denote default builder tool do not uglify JS bundles
devMode: false

# If we have public CDN domain name like "http://cdn.dianrong.com"
staticAssetsURL: ""

# Manually set bundle file name for 3rd-party libaraies, otherwise browserify
# will bundle them with every package that depends on them.
vendorBundleMap:
  core: # bundle name
      - lodash
      - q

packageContextPathMapping:
    # Package short name - route path map, used by express server.
    # By default, every package's is mapped to a route context path "/<package short name>"
    # e.g.
    #   if package name is "@dr/example-dr", default route root path will be `/example-dr`
    # If you want change this rule, config route path here.
    home: /

# During developing, you can set this to `true` to make every package to a single bundle
bundlePerPackage: false
