# If you are not familiar with YAML format just like me, read https://en.wikipedia.org/wiki/YAML
# PLEASE DON'T MODIFY THIS FILE, instead you may create a local file called `config.local.yaml`
# to overwrites this file.
srcDir: src
destDir: dist
port: 14333
# set max-age property of the Cache-Control header in `ms` format, see https://github.com/expressjs/serve-static
cacheControlMaxAge: "365 days"
packageScopes:
  - dr
  # dr-core is considered as special packages which will be loaded before other packages
  - dr-core

# default package recipe folder
# we can change this to another folder for production environment
recipeFolder: package-recipe

# recipeFolder: developer

nodeRoutePath: /

# enable devMode to denote default builder tool do not uglify JS bundles
devMode: false

# If we have public CDN domain name like "http://cdn.dianrong.com"
staticAssetsURL: ""

# Manually set bundle file name for 3rd-party libaraies, otherwise browserify
# will bundle them with every package that depends on them.
vendorBundleMap:
  core: # bundle name
      - lodash
      - q
      - jquery
      - eventemitter3

# Global `browserify.bundle()` `noParse` option, there is also a package specific `dr.browserifyNoParse`
# available option in individual package.json file
browserifyNoParse:
    - q
    - lodash
    - jquery
    - gsap

packageContextPathMapping:
    # Package short name - route path map, used by express server.
    # By default, every package's is mapped to a route context path "/<package short name>"
    # e.g.
    #   if package name is "@dr/example-dr", default route root path will be `/example-dr`
    # If you want change this rule, config route path here.
    poc-home: /

# During developing, you can set this to `true` to make every package to a single bundle
bundlePerPackage: false
